export enum Superpowers {
  Flight = 'Flight',
  Invisibility = 'Invisibility',
  SuperStrength = 'Super Strength',
  FireManipulation = 'Fire Manipulation',
  SuperSpeed = 'Super Speed',
  Telepathy = 'Telepathy',
  HardLightConstructs = 'Hard Light Constructs',
  Invulnerability = 'Invulnerability',
  Telekinesis = 'Telekinesis',
  // Shapeshifting = 'Shapeshifting',
  // ThePowerCosmic = 'The Power Cosmic',
  // Immortality = 'Immortality',
  // TimeTravel = 'Time Travel',
  // MindControl = 'Mind Control',
  // Teleportation = 'Teleportation',
  // MagneticManipulation = 'Magnetic Manipulation',
  // HealingFactor = 'Healing Factor',
  // AtomicManipulation = 'Atomic Manipulation',
  // ControllingWeather = 'Controlling Weather',
  // XRayVision = 'X-Ray Vision',
  // ElectricManipulation = 'Electric Manipulation',
  // IceManipulation = 'Ice Manipulation',
  // SpiderWebs = 'Spider Webs',
  // ForceFieldProjection = 'Force Field Projection',
  // RealityWarping = 'Reality Warping',
  // WeaponHands = 'Weapon Hands',
  // HeatVision = 'Heat Vision',
  // SuperIntelligence = 'Super Intelligence',
  // DangerWarning = 'Danger Warning',
  // PowerStealing = 'PowerStealing',
}

export const superpowers: Superpowers[] = [
  Superpowers.Telekinesis,
  Superpowers.Invulnerability,
  Superpowers.Flight,
  Superpowers.Invisibility,
  Superpowers.Telepathy,
  Superpowers.FireManipulation,
  Superpowers.SuperSpeed
]